from sentence_transformers import util


class DiagnoseSimilarity:
    def __init__(self, model) -> None:
        self.diags = [
            "Abklärung instab. Ang. Pect.",
            "Bei klin. Hinweisen auf Zinkmangel z.B. Alopezie",
            "bei Neugeb. (Mutter HIV-pos.)",
            "benötigt strenge medizinische Indikation",
            "Biologica Therapie",
            "Blutentnahme aus der Vene - Kassenleistung",
            "CK erhöht",
            "Diabetes Mellitus",
            "einmalige Erstbestimmung",
            "exponierte Berufsgruppen (Nadelstichverletztung)",
            "Extrauteringravidität",
            "Gesamtbilirubin erhöht",
            "Harneiweiß negativ",
            "HAV IgM positiv",
            "HBc AK positiv",
            "HBc IgM wegen pathologischem Suchtest",
            "HBc IgM zur Verlaufskontrolle",
            "HBe AG wegen pathologischem Suchtest",
            "HBe AG zur Verlaufskontrolle",
            "HBe AK wegen pathologischem Suchtest",
            "HBe AK zur Verlaufskontrolle",
            "HBs AG positiv",
            "HBs AG positiv, vor Einstellung auf Biologica (inaktiv)",
            "HBV PCR positiv",
            "HCV AK positiv, zur Therapieentscheidung",
            "HCV PCR positiv",
            "HIV-infizierte zur Therapiekontrolle",
            "Hypercholesterinämie",
            "immer verrechenbar außer bei Drogenharn",
            "klinische Anamnese und Hauttestung erfolgt",
            "Lithiumpräparattherapie",
            "M-Gradienten in der Serumelektrophorese",
            "MUKIPA",
            "MUKIPA oder OP-Vorbereitung",
            "nur bei pathologischen Schilddrüsenhormonen oder bekannter Schilddrüsenerkrankung verrechenbar. (inaktiv)",
            "nur im Rahmen einer strukturierten Substitutionstherapie verrechenbar, gemeinsam mit KREA-U anfordern",
            "nur zur Anämiediagnostik",
            "nur zur Verlaufskontrolle von gesicherten malignen Tumoren (Magen oder Ovarial CA)",
            "nur zur Verlaufskontrolle von gesicherten malignen Tumoren (malignes Melanom)",
            "OP-Vorbereitung",
            "OP-Vorbereitung oder Transfusionsbedarf oder Antikoagulantientherapie",
            "pathologisches TSH",
            "PSA - Verlaufskontrolle wegen gesichertem malignen Tumor",
            "PSA - Vorsorge (> 50 Jahre)",
            "PSA wegen hereditärer Prädisposition (45 – 50 Jahre)",
            "RUB IgM positiv",
            "Schilddrüsen-Tumor",
            "SD-Therapie",
            "ß-HCG als Tumormarker",
            "strukturierte Substitutionstherapie",
            "Substitutionstherapie",
            "Therapiekontrolle",
            "Thrombophilieabklärung (Embolie, TVT)",
            "Toxo IgG positiv",
            "Transfusionsbedarf",
            "Überwachung von Risikoschwangerschaft",
            "bitte vermutete Autoimmunerkrankung in der Diagnose angeben",
            "V.a. Diabetes Mellitus",
            "V.a. Gerinnungsstörung",
            "V.a. Gewürzallergie, nicht-mögliche Hauttestung, klinische Anamnese erfolgt",
            "V.a. Gräserallergie, nicht-mögliche Hauttestung, klinische Anamnese erfolgt",
            "V.a. hämatologische Systemerkrankung",
            "V.a. Histaminintoleranz",
            "V.a. HIV Infektion",
            "V.a. Inhalationsallergie, nicht-mögliche Hauttestung, klinische Anamnese erfolgt",
            "V.a. Kontaktallergie, nicht-mögliche Hauttestung, klinische Anamnese erfolgt",
            "V.a. M.Reiter",
            "V.a. Morbus Basedow",
            "V.a. Morbus Bechterew",
            "V.a. Morbus Wilson",
            "V.a. Myocardinfarkt",
            "V.a. Nahrungsmittelallergie, nicht-mögliche Hauttestung, klinische Anamnese erfolgt",
            "V.a. Nussallergie, nicht-mögliche Hauttestung, klinische Anamnese erfolgt",
            "V.a. Pankreas-Insuffizienz",
            "V.a. schweren Immundefekt",
            "V.a. Serotoninmangel",
            "V.a. TBC",
            "V.a. Thrombophilie",
            "V.a. Thyreoiditis",
            "V.a. Verbrauchskoagulopathie",
            "V.a. Vit D3 Mangel",
            "V.a. Zöliakie",
            "Vor Einstellung auf Biologica",
            "Epilepsiebehandlung",
            "V. a. Muskelerkrangungen",
            "V. a. Epilepsie",
            "V. a. Hormonstörung",
            "Morbus Crohn/Colitis Diagnostik",
            "Abgrenzung CED - Reizdarm",
            "Verlaufskontrolle Colitis Ulcerosa",
            "Verlaufskontrolle Morbus Crohn",
            "ab 40 LJ bei hohem Risiko für Prostatakarzinom (erstgradige Verwandte, familiäre Häufung)",
            "ab 40 LJ bei bekannter o. V.a. BRCA1/2-Mutation",
            "bei Nachweis eines Hypogonadismus vor einer Testosteronsubstitution",
            "unter Testosteronsubstitution (im ersten Jahr halbjährlich, anschließend jährlich)",
            "abnormale digital-rektale Untersuchung bzw. konkreter Krebsverdacht (tastbare Knoten)",
            "Verlaufskontrolle von gesichertem malignen Tumor",
            "begründeter Verdacht auf Tumor",
            "Erhöhtes Gestoserisiko bei anamnestischer Präeklampsie ab der 20. SSW",
            "Eiweißausscheidung im Harn über 1g pro 24h bei Schwangerschaftshypertonie ab der 20 SSW",
            "Prostatahyperplasie",
            "Verrechnung an die AUVA",
            "Helicobacter Pylori Antigentest positiv",
            "patholog. Schilddrüsenhormone",
            "Schilddrüsenerkrankung",
            "Rheumatoide Arthritis (RA)=Chronische Polyarthritis(CP,PCP)",
            "Juvenile idiopathische Arthritis (JIA)= juvenile rheumatoide Arthritis (JRA)=juvenile chronische Arthritis (JCA), Morbus Still",
            "Systemischer Lupus erythematodes (LE,SLE)",
            "Sjögren Syndrom(SjS)",
            "Systemische Sklerodermie (SSc)",
            "Dermatomyositis (DM)",
            "Polymyositis (PM)",
            "Mixed Connective Tissue Disease=Sharp Syndrom=Mischkollagenose (MCTD)",
            "Autoimmunhepatitis (AIH)",
            "CREST-Syndrom (Calcinosis cutis, Raynaud-Phänomen, Esophagus-Motilitätsstörung, Sklerodaktylie, Teleangiektasie)",
            "Primär biliäre Cholangitis = Primär biliäre Cirrhose (PBC)",
            "Primär sklerosierende Cholangitis (PSC)",
            "Erhöhte Eiweißausscheidung",
            "V.a. Paraproteinämie",
            "Positiver Antigen-Test",
            "Negativer Antigentest, jedoch Symptomhäufung und stark ausgeprägte Intensität, sowie anamnestischer Kontakt zu einer COVID-19 erkrankten Person.",
            "Sachverhalt nicht eindeutig trotz Einsatz aller serologischen Mittel",
            "Sero-negativ trotz klinischer Erscheinungen, die auf HIV-Infektion schließen lassen",
            "Schwanger nach diagnostizierter HIV",
            "Akute HIV Infektion",
            "PAP III",
            "Abklärung unklarer Abstriche",
            "Patientinnen mit besonderem Risiko",
            "CoV-2 Infektionssymptome",
            "jährliches Screening",
            "Kontrolle nach pos. Ergebnis Voruntersuchung",
            "Im Rahmen der Myelomdiagnostik verrechenbar",
            "V.a. hämorrhagische Diathese",
            "Abklärung Gerinnungsstörung bei verlängerten Globaltests (PTZ-Quick und/oder PTT)",
            "Thrombophilie Diagnostik",
            "V.a. Sarkoidose/M. Böck",
        ]
        self.model = model
        self.diag_embeddings = model.encode(self.diags)

    def show_similarity(self, input):
        similarity = self.calculate_similarity(input)
        for a, b in zip(self.diags, similarity.tolist()[0]):
            print(f"{a}: {b}\n")

    def calculate_similarity(self, input: str):
        input_embedding = self.get_input_embedding(input)
        return util.pytorch_cos_sim(input_embedding, self.diag_embeddings)

    def get_input_embedding(self, input: str):
        input_embedding = self.model.encode(input)
        return input_embedding
